language: php

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] ; then
        phpunit --coverage-clover=coverage.xml
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    else
        phpunit
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

#Borrowed from https://github.com/humanmade/backupwordpress/blob/master/.travis.yml