language: php

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer update; composer install --dev;

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] ; then
        ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml
        ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.xml
    else
        ./vendor/bin/phpunit -c phpunit.xml
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

#Borrowed from https://github.com/humanmade/backupwordpress/blob/master/.travis.yml